name: Build & Upload Binaries

on:
  release:
    types: [published]   # Trigger when a release is published

jobs:
  build:
    name: Build prebuilt binaries
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20]   # [16, 18, 20, 22, 24, 25]
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install distutils compatibility
        run: pip install setuptools

      - name: Checkout Git Source
        uses: actions/checkout@v6e

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build addon
        run: npm run build   # or: node-gyp rebuild

      - name: Create prebuild (binary)
        run: npx prebuildify --napi --target "node@$(node -p 'process.version.slice(1)')"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-${{ matrix.os }}-node${{ matrix.node-version }}
          path: prebuilds/
          retention-days: 3

  release:
    name: Attach prebuilt binaries to GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install distutils compatibility
        run: pip install setuptools

      - name: Checkout Git Source
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./prebuilds

      - name: List downloaded files
        run: ls -R ./prebuilds

      - name: Upload binaries to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(find ./prebuilds -type f); do
            echo "Uploading $file"
            gh release upload "${{ github.event.release.tag_name }}" "$file" --clobber
          done
